#!/bin/sh
#

# For RHEL Linux systems
# streamer          Start/Stop sync
#
# chkconfig: 35 98 10
# description: streamer service
# processname: streamer
# config:
# pidfile: /var/run/streamer.pid

# For Ubuntu Linux systems
### BEGIN INIT INFO
# Provides:          streamer
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ZMQ streamer
# Description:       Start the streamer service to stream images via ZMQ
### END INIT INFO


# Use Java 7
PATH=/opt/jre/bin:$PATH
export PATH

USER=det
HOME=/opt/streamer
SU="su --login  $USER --command  "

LOGFILE=/var/log/streamer

touch $LOGFILE
chown $USER $LOGFILE

case "$1" in
start)
  $SU "PATH=/opt/jre/bin:$PATH $HOME/latest/bin/streamer -d /ramdisk -p 8080 > $LOGFILE 2>&1 &"
  ;;
stop)
  $SU "pkill -f 'java .* $HOME' >> $LOGFILE 2>&1 &"
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "usage: $0 (start|stop|restart|help)"
esac