#!/bin/sh
#
# streamer          Start/Stop sync
#
# chkconfig: 35 98 10
# description: streamer service
# processname: streamer
# config:
# pidfile: /var/run/streamer.pid

# Use Java 7
PATH=/opt/jre/bin:$PATH
export PATH

USER=det
HOME=/opt/streamer
SU="su --login  $USER --command  "

LOGFILE=/var/log/streamer

touch $LOGFILE
chown $USER $LOGFILE

case "$1" in
start)
  $SU "PATH=/opt/jre/bin:$PATH $HOME/latest/bin/streamer -p 8080 > $LOGFILE 2>&1 &"
  ;;
stop)
  $SU "pkill -f 'java .* $HOME' >> $LOGFILE 2>&1 &"
  ;;
\*)
  echo "usage: $0 (start|stop|help)"
esac